spring.application.name=ChatApp
spring.security.user.name=Aaditya
spring.security.user.password=12345



#DB Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/ChatApplication
spring.datasource.username=postgres
spring.datasource.password=admin