spring.application.name=ChatApp
spring.security.user.name=Aaditya
spring.security.user.password=12345

logging.level.org.springframework.security=DEBUG


#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ChatApplication
spring.datasource.username=postgres
spring.datasource.password=admin

#Defines driver for postgresSQL
spring.datasource.driver-class-name=org.postgresql.Driver

#optimizes SQL queries for PostgresSQL:-
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.default_schema=Chat_Application


#Controls how Hibernate handles database schema changes.
#Ensures tables are created if they don?t exist.
#Keeps existing data safe.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# It executes the schema.sql file
spring.sql.init.mode=always
spring.sql.init.platform=postgres

@org.springframework.beans.factory.annotation.Autowired.required=true



#logging.level.root=DEBUG


spring.security.oath2.client.registration.google.client-id= paste here google client ID
spring.security.oath2.client.registration.google.client-secret= paste here google client secret

#Both will be generated using google cloud platform